'use client'

import Head from "next/head";
import Logo from "../Logo/Logo";
import Navigation from "../Navigation/Navigation";
import { HeaderContainer } from "../styled/HeaderStyled";

const Header = () => {
    return (
        <>
            <Head>
            <title>Tour Booking</title>
            <meta name="description" content="Generated by create next app" />
            {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderContainer>
                <Logo />
                <Navigation />
            </HeaderContainer>
        </>
    );
}
export default Header;