import Head from 'next/head'
import Header from '@/components/common/Header/Header'
import Container from '@/components/common/Container/Container'
import BackGroundImage from '@/components/common/BackGroundImage/BackGroundImage'
import Filters from '@/components/common/Filters/Filters'
import PopularSearches from '@/components/common/PopularSearches/PopularSearches'
import Tours from '@/components/Tours/Tours'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tour Booking</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackGroundImage />
      <Header />
      <Filters />
      <Container>
        <PopularSearches />
        <Tours />
      </Container>
    </>
  )
}
